hybrid_quantum_algorithms/QAOA/utils_qaoa.py
*Description of changes:* Fix small typo
=> Fix typo in comment

pennylane/0_Getting_started.ipynb, pennylane/2_Graph_optimization_with_QAOA.ipynb
Included a warning for a high cost when running hybrid algorithms on a QPU.
=> Update the docs

CODEOWNERS
=> infra: Add team to CODEOWNERS

hybrid_quantum_algorithms/VQE_Chemistry/VQE_chemistry_braket.ipynb
=> Fix Metadata Issue

README.md
=> Update README.md with noise simulation

examples/braket_features/Simulating_Noise_On_Amazon_Braket.ipynb
…in notebook Simulating_Noise_On_Amazon_Braket
*Issue #, if available:* N/A
*Description of changes:* Correcting minor typos and adding a reference in the introduction
=> Correcting minor typos and adding a reference in introduction

environment.yml, test/notebook_tests/test_notebooks.py
=> Update environment file, test fixes

examples/braket_features/Verbatim_Compilation.ipynb
Adding verbatim compilation notebook
=> Add verbatim compilation notebook

examples/braket_features/Verbatim_Compilation.ipynb
=> minor fixes

examples/getting_started/3_Deep_dive_into_the_anatomy_of_quantum_circuits.ipynb
Demonstrate simultaneous measurement of qwc observables when `shot>0` and exact calculation of expectation for noncommuting observables.
=> Simultaneous measurement in anatomy notebook

examples/quantum_annealing/Dwave_GraphPartitioning.ipynb, examples/quantum_annealing/Dwave_MaximumCut.ipynb, examples/quantum_annealing/Dwave_MinimumVertexCoverProblem.ipynb, examples/quantum_annealing/Dwave_TravelingSalesmanProblem/Dwave_TravelingSalesmanProblem.ipynb
Remove all other mentions of Advantage_system1 for device arns
=> Remove all other mentions of Advantage_system1 for device arns

examples/getting_started/2_Running_quantum_circuits_on_QPU_devices.ipynb
=> fix: remove unnecessary semicolons

examples/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs.ipynb
=> Fix an apparent typo

examples/pennylane/3_Quantum_chemistry_with_VQE.ipynb
=> Correct links in PennyLane VQE notebook

examples/hybrid_jobs/3_Bring_your_own_container/algorithm_script.py, examples/pennylane/0_Getting_started.ipynb
Update example notebooks to be compatible with future deprecations.
=> Update examples for PennyLane v0.19

environment.yml, examples/advanced_circuits_algorithms/Randomness/Randomness_Generation.ipynb
Added ecos dependency for running tests locally without any issues for Randomness Generation notebook. This dependency was recently updated in NBIs. 
=> fix: deps for cvxpy

test/notebook_tests/test_notebooks.py
Temporarily excluding jobs notebooks from testing since causing timeout issues. 
=> change: temporarily exclude NB's from testing

examples/advanced_circuits_algorithms/QPE/utils_qpe.py, examples/hybrid_quantum_algorithms/QAOA/utils_qaoa.py
=> Minor corrections

examples/advanced_circuits_algorithms/QPE/utils_qpe.py, examples/hybrid_quantum_algorithms/QAOA/utils_qaoa.py
=> Minor name corrections (#109)

examples/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs.ipynb
=> fix: Fix link to the QAOA algorithm script

examples/advanced_circuits_algorithms/Grover/Grover.ipynb
=> fix: Remove extra indent

test/notebook_tests/test_notebooks.py
change: Exclude bring your own container notebook from notebook testing.
=> change: Exclude bring your own container notebook from notebook testing.

test/notebook_tests/test_notebooks.py
fix: Make it so notebook avoids the container test.
=> fix: Make it so notebook avoids the container test.

examples/braket_features/Verbatim_Compilation.ipynb
=> fix: use of undeclared variable.

examples/getting_started/2_Running_quantum_circuits_on_QPU_devices.ipynb, examples/getting_started/3_Deep_dive_into_the_anatomy_of_quantum_circuits.ipynb
Added OQC device to notebooks in getting-started and made associated text changes.
=> Feature: add OQC device 

test/notebook_tests/test_notebooks.py
fix: Rigetti verbatim comp run for test only
=> fix: Rigetti verbatim comp run for test only

test/notebook_tests/test_notebooks.py
Removing verbatim from tests temporarily to avoid test failures. 
=> change: remove verbatim NB from tests

test/notebook_tests/conftest.py, test/notebook_tests/test_notebooks.py
* Simplify test setup and filtering by removing hard coding device availability and specific device arns. 
* Removed the copying of notebooks and replacement of S3 bucket names.
=> fix: Simplify test setup and filtering

environment.yml
change: Bump the boto* and awscli dependency versions
=> change: Bump the boto* and awscli dependency versions

.github/ISSUE_TEMPLATE/bug_report.md
Adding known workaround section in the the bug report. 
=> fix: bug report template

environment.yml
- Updates outdated dependencies in environment.yml
=> fix: dependencies in environment.yml

examples/braket_features/Noise_models/Noise_models_on_Rigetti_AspenM1.ipynb
=> fix: broken link to notebook

environment.yml, test/notebook_tests/test_notebooks.py
Update environment to require Strawberry Fields, and skip the Borealis beginner notebook in tests because of a commented-out cell.
=> Update environment & test for photonics

README.md
=> Update README.md for photonics

examples/getting_started/1_Running_quantum_circuits_on_simulators/1_Running_quantum_circuits_on_simulators.ipynb, examples/getting_started/2_Running_quantum_circuits_on_QPU_devices/2_Running_quantum_circuits_on_QPU_devices.ipynb
=> fix: removing unused imports, semicolons, and s3 references

CODEOWNERS
=> infra: Update team for CODEOWNERS

README.md
https://github.com/aws/amazon-braket-examples/issues/165
fix: Fix README for broken example links.
=> fix: Fix README for broken example links.

examples/braket_features/Simulating_Advanced_OpenQASM_Programs_with_the_Local_Simulator.ipynb
=> fix: capitalize Bell

examples/hybrid_jobs/4_Embedded_simulators_in_Braket_Jobs/Embedded_simulators_in_Braket_Jobs.ipynb, examples/hybrid_jobs/5_Parallelize_training_for_QML/Parallelize_training_for_QML.ipynb, examples/hybrid_jobs/6_QNSPSA_optimizer_with_embedded_simulator/qnspsa_with_embedded_simulator.ipynb
=> Add notice about default hybrid jobs limits

examples/analog_hamiltonian_simulation/00_Introduction_of_Analog_Hamiltonian_Simulation_with_Rydberg_Atoms.ipynb
=> polished notebook 00

examples/analog_hamiltonian_simulation/utils.py
plt.show() added to each AHS utility function that creates a plot.
=> expliticly showing plots in utility functions

examples/pennylane/2_Graph_optimization_with_QAOA/2_Graph_optimization_with_QAOA.ipynb
=> Inline matplotlib plot for 2_Graph_optimization_with_QAOA

examples/quantum_annealing/Dwave_Factoring/Dwave_factoring.ipynb, examples/quantum_annealing/Dwave_StructuralImbalance/Dwave_StructuralImbalance.ipynb
=> Pin Jinja2 versions in D-Wave notebooks

environment.yml
Updating with latest versions. Tested dependency conflicts
=> deps: update dependencies with latest

examples/pennylane/6_Adjoint_gradient_computation/6_Adjoint_gradient_computation.ipynb
Update example to use 8 electrons
=> fix: update AG example to 8 electrons

examples/hybrid_jobs/7_Submitting_notebooks_to_Jobs/1_Submit_notebook.ipynb, examples/hybrid_jobs/7_Submitting_notebooks_to_Jobs/src/0_Getting_started_papermill.ipynb, examples/hybrid_jobs/7_Submitting_notebooks_to_Jobs/src/helper_script.py
None
Changes are only for notebook job submission.
1. helper script: With this change, the helper script can be used to submit notebook directly in Bracket console. Upload notebook as "Input Data" with channel name "input". 
2. Tag and QPU cost reduction changes to notebooks
=> Papermill demo

examples/pennylane/3_Hydrogen_Molecule_geometry_with_VQE/3_Hydrogen_Molecule_geometry_with_VQE.ipynb
=> fix: PL doc link

test/integ_tests/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job_mocks.py, test/integ_tests/hybrid_jobs/1_Quantum_machine_learning_in_Amazon_Braket_Hybrid_Jobs/Quantum_machine_learning_in_Amazon_Braket_Hybrid_Jobs_mocks.py, test/integ_tests/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs_mocks.py, test/integ_tests/hybrid_jobs/4_Embedded_simulators_in_Braket_Jobs/Embedded_simulators_in_Braket_Jobs_mocks.py, test/integ_tests/hybrid_jobs/5_Parallelize_training_for_QML/Parallelize_training_for_QML_mocks.py, test/integ_tests/mock_utils.py
=> update: making changes to support least mocking tests in different regions.

environment.yml, nbi/buildspec.yml
=> fix: adding algorithm library as a dependency in the buildspec

.github/workflows/python-package.yml
=> update: adding build for python 3.10

examples/braket_features/Simulating_Advanced_OpenQASM_Programs_with_the_Local_Simulator.ipynb
- Documentation fix around openqasm support provided by Braket.
=> fix: documentation for openqasm example

.github/workflows/conda-build.yml, .github/workflows/python-package.yml, environment.yml
=> Deprecate Python 3.7

environment.yml
fixes incompatibility with pennylane<0.29.1
=> fix: pin autoray version

environment.yml
=> Update Braket and PL libraries

.github/workflows/conda-build.yml, test/integ_tests/test_all_notebooks.py
This example is running too long so this will be a temporary removal while an RCA is done on the time
=> fix: exclude AHS example 4 from integ tests

environment.yml, test/integ_tests/analog_hamiltonian_simulation/04_Maximum_Independent_Sets_with_Analog_Hamiltonian_Simulation_mocks.py
feat: upgrade notebooks to python3.9
=> feat: upgrade notebooks to python3.9

README.md
*Issue #, if available:* N/A
*Description of changes:* Add support details to the README.
=> documentation: Update README with support info

environment.yml, examples/qiskit/0_Getting_Started.ipynb, test/integ_tests/qiskit/0_Getting_Started_mocks.py, test/integ_tests/requirements.txt
=> feature: adding qiskit provider to NBI dependencies.

examples/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/qaoa/qaoa_utils.py
https://github.com/aws/amazon-braket-containers/commit/3c3b797c303bda9882c1ba23a3853f06e75c5282
For the TF 2.11.0 update
=> fix: use the legacy SGD optimizer

environment.yml
=> fix: update the algorithm library and SDK versions

.gitignore
=> Add JetBrains files to .gitignore

environment.yml
=> change: update dependency for algorithm library

environment.yml
=> fix: update the pennylane-plugin to 1.15.1

examples/braket_features/TN1_demo_local_vs_non-local_random_circuits.ipynb
comment out failure cell example for the tn1 example. This cell takes a considerable amount of time to run. 
=> fix: comment out failure cell example for the tn1 example

environment.yml, examples/braket_features/Error_Mitigation_on_Amazon_Braket.ipynb, test/integ_tests/test_all_notebooks.py
=> Add error mitigation notebook

examples/braket_features/Error_Mitigation_on_Amazon_Braket.ipynb, examples/braket_features/phase_estimation.py
Simplify example notebook for Aria error mitigation.
Added cost tracking to Aria example notebook. Refactored phase estimation circuit code to separate .py file.  
=> fix: notebook update

environment.yml
https://github.com/aws/aws-cli/issues/8036
=> Py yaml fix

examples/hybrid_jobs/3_Bring_your_own_container/dockerfile
=> fix: use the latest image tag

nbi/buildspec.yml
=> fix: multithreaded builds for conda pack

environment.yml
=> feat: update dependency for aria2

examples/qiskit/0_Getting_Started.ipynb, test/integ_tests/test_all_notebooks.py
Adding a test to check if any of the cell output has errors. The Qiskit example notebook has errors so I have reset the output until the problem is fixed.
=> update: adding test to check cell outputs

.github/workflows/conda-build.yml
=> infra: parallelize extra directory teardown

README.md
=> docs: remove annealing from docs

examples/hybrid_jobs/0_Creating_your_first_Hybrid_Job/algorithm_script.py, examples/hybrid_jobs/0_Creating_your_first_Hybrid_Job/algorithm_script_parametrized_circuit.py
Fix parameter to avoid conflicts with OpenQASM reserved name.
=> fix: set parameter name to an allowed name

.github/workflows/python-package.yml
=> infra: use macos  large runners

.github/dependabot.yml
I do not want to review 1 million dependency upgrade PRs and I am sure others don't either.
=> fix: have dependabot batch updates

requirements.txt
=> infra: remove keras, ecos to reduce requirements size

examples/pennylane/0_Getting_started/0_Getting_started.ipynb
=> fix: queue info jobs field

examples/pennylane/2_Graph_optimization_with_QAOA/2_Graph_optimization_with_QAOA.ipynb
=> fix: pandas import

test/integ_tests/conftest.py, test/integ_tests/hybrid_jobs/0_Creating_your_first_Hybrid_Job/0_Creating_your_first_Hybrid_Job_mocks.py, test/integ_tests/mock_utils.py, test/integ_tests/test_all_notebooks.py
Add mocking for hybrid job first example. Add region property to Boto3SessionAll wrapper
=> feat: mock getting started hybrid job example

test/integ_tests/hybrid_jobs/0_Creating_your_first_Hybrid_Job/0_Creating_your_first_Hybrid_Job_mocks.py, test/integ_tests/hybrid_jobs/1_Quantum_machine_learning_in_Amazon_Braket_Hybrid_Jobs/Quantum_machine_learning_in_Amazon_Braket_Hybrid_Jobs_mocks.py, test/integ_tests/mock_utils.py, test/integ_tests/test_all_notebooks.py
Mock machine learning hybrid job test.
Integ test passing in LEAST and ALL mocking
=> test: mock machine learning job notebook

test/integ_tests/hybrid_jobs/2_Using_PennyLane_with_Braket_Hybrid_Jobs/Using_PennyLane_with_Braket_Hybrid_Jobs_mocks.py, test/integ_tests/test_all_notebooks.py
=> fix: adding PL example with HJ again

test/integ_tests/hybrid_jobs/0_Creating_your_first_Hybrid_Job/0_Creating_your_first_Hybrid_Job_mocks.py, test/integ_tests/hybrid_jobs/1_Quantum_machine_learning_in_Amazon_Braket_Hybrid_Jobs/Quantum_machine_learning_in_Amazon_Braket_Hybrid_Jobs_mocks.py, test/integ_tests/hybrid_jobs/2_Using_PennyLane_with_Braket_Hybrid_Jobs/Using_PennyLane_with_Braket_Hybrid_Jobs_mocks.py, test/integ_tests/mock_utils.py, test/integ_tests/pennylane/0_Getting_started/0_Getting_started_mocks.py, test/integ_tests/test_all_notebooks.py
Mock getting started PL notebook. Move get job and get role mocks into shared util
Tested in LEAST and ALL
=> test: mock PL getting started

test/integ_tests/hybrid_jobs/1_Quantum_machine_learning_in_Amazon_Braket_Hybrid_Jobs/Quantum_machine_learning_in_Amazon_Braket_Hybrid_Jobs_mocks.py, test/integ_tests/hybrid_jobs/2_Using_PennyLane_with_Braket_Hybrid_Jobs/Using_PennyLane_with_Braket_Hybrid_Jobs_mocks.py, test/integ_tests/mock_utils.py, test/integ_tests/pennylane/0_Getting_started/0_Getting_started_mocks.py, test/integ_tests/pennylane/2_Graph_optimization_with_QAOA/2_Graph_optimization_with_QAOA_mocks.py, test/integ_tests/test_all_notebooks.py
mock graph qaoa notebook and move get job result mock to common util.
passing in least and all
=> test: graph qaoa mocks

nbi/buildspec.yml
=> fix: unpin miniconda from latest for SHA verification

test/integ_tests/hybrid_jobs/1_Quantum_machine_learning_in_Amazon_Braket_Hybrid_Jobs/Quantum_machine_learning_in_Amazon_Braket_Hybrid_Jobs_mocks.py, test/integ_tests/mock_utils.py, test/integ_tests/pennylane/0_Getting_started/0_Getting_started_mocks.py, test/integ_tests/pennylane/2_Graph_optimization_with_QAOA/2_Graph_optimization_with_QAOA_mocks.py, test/integ_tests/pennylane/3_Hydrogen_Molecule_geometry_with_VQE/3_Hydrogen_Molecule_geometry_with_VQE_mocks.py, test/integ_tests/test_all_notebooks.py
=> fix: enabling testing of pennylane 03

test/integ_tests/requirements.txt
=> fix test requirements to use PL < 0.32

requirements.txt
=> feat: bump BDK version

test/integ_tests/requirements.txt
=> infra: pin qiskit-braket-provider

requirements.txt
This will enable reservations for Braket Direct
=> Update Braket libraries

pyproject.toml
=> fix: add file selection for example files only

.github/workflows/code-freeze.yml
Update code freeze logic (support no unfrozen prefix)
=> infra: update code freeze workflow

examples/advanced_circuits_algorithms/Simons_Algorithm/Simons_Algorithm.ipynb, examples/braket_features/Using_The_Adjoint_Gradient_Result_Type.ipynb, examples/hybrid_jobs/6_QNSPSA_optimizer_with_embedded_simulator/source_scripts/benchmark_qaoa_converge_speed.py, examples/hybrid_quantum_algorithms/QAOA/QAOA_braket.ipynb
=> remove unneeded pip installations from code

examples/pennylane/3_Hydrogen_Molecule_geometry_with_VQE/3_Hydrogen_Molecule_geometry_with_VQE.ipynb
=> Drop number of iterations for the VQE example

nbi/buildspec.yml
Artifact size before: `382M`
Artifact size after: `357M`
Runtime does go up by ~30 seconds.
=> raise compression to 16

requirements.txt
=> infra: raise the Braket SDK to 1.68.2

README.md, pyproject.toml, test/repo_tests/test_readme.py
Updating the list of notebooks we have in this repository. It's been quite a while since we've done this, so we're out-of-date. I will also look into tests to see if we can detect this issue more quickly. 
=> docs: updating README with info about notebooks

requirements.txt
=> chore: bump BDK version

requirements.txt
=> infra: update Pennylane to 0.35

examples/hybrid_jobs/2_Using_PennyLane_with_Braket_Hybrid_Jobs/Using_PennyLane_with_Braket_Hybrid_Jobs.ipynb, examples/pennylane/6_Adjoint_gradient_computation/6_Adjoint_gradient_computation.ipynb
=> fix: broken links in notebooks

examples/qiskit/0_Getting_Started.ipynb
=> Update AWSBraketProvider -> BraketProvider

examples/analog_hamiltonian_simulation/07_Simulating_Lattice_Gauge_Theory_with_Rydberg_Atoms.ipynb, examples/analog_hamiltonian_simulation/08_Maximum_Weight_Independent_Set.ipynb
update cost tracker for new AHS examples
=> fix: update cost tracker for new AHS examples

examples/analog_hamiltonian_simulation/01_Introduction_to_Aquila.ipynb
fix: conditionally print rydberg local data
=> fix: conditionally print rydberg local data

environment.yml, nbi/buildspec.yml
=> change: adding libstd to the Braket conda env

test/integ_tests/default_data/default_results.json
=> fix: add iqm metadata

test/integ_tests/advanced_circuits_algorithms/Randomness/rand_results.json
=> fix: update randomness mocks for new devices

test/integ_tests/test_all_notebooks.py
Temporarily excluding notebooks for testing in eu-north-1 due to lack of simulator support.
=> fix: exclude job based NBIs in eu-north-1

test/integ_tests/test_all_notebooks.py
=> test: remove testing arn simulator notebooks

requirements.txt
Update to latest released versions of BDK packages.
=> change: Update BDK package versions

requirements.txt
=> fix: Update Python requirements to latest Braket package versions

requirements.txt
=> infra: bump the SDK version to 1.90.0

test/integ_tests/hybrid_jobs/0_Creating_your_first_Hybrid_Job/0_Creating_your_first_Hybrid_Job_mocks.py, test/integ_tests/qiskit/0_Getting_Started_mocks.py
Fixing a bug in the integ test mock that got introduced with Ankaa-3 changes.
=> fix: Fixed Ankaa-3 integ test

test/integ_tests/hybrid_jobs/0_Creating_your_first_Hybrid_Job/0_Creating_your_first_Hybrid_Job_mocks.py
Refactor create_job mocking to use return_value instead of side_effect
=> fix: Modified integ tests

requirements.txt
=> feat: Update Braket SDK with Forte Enterprise 1

test/integ_tests/test_all_notebooks.py
=> infra: remove tn1 notebook from testing

nbi/buildspec.yml
=> infra: accept conda tos

.github/workflows/check-format.yml, .github/workflows/python-package.yml, examples/analog_hamiltonian_simulation/09_Noisy_quantum_dynamics_for_Rydberg_atom_arrays.ipynb, examples/braket_features/program_sets/02_Expectation_value_calculations_with_program_sets.ipynb, pyproject.toml, requirements.txt
=> feat: remove unsupported python 3.9
