amazon-braket/amazon-braket-examples

braket_features/Using_the_tensor_network_simulator_TN1.ipynb
We uploaded the original version of the TN1 notebook without doc links. This PR fixes that.
=> Fix links to nowhere in TN1 notebook

examples/pennylane/1_Parallelized_optimization_of_quantum_circuits.ipynb, examples/pennylane/2_Graph_optimization_with_QAOA.ipynb, examples/pennylane/3_Quantum_chemistry_with_VQE.ipynb
The new core of PennyLane (formerly known as "tape mode") has been the default since PennyLane v0.14 ([release notes](https://pennylane.readthedocs.io/en/stable/development/release_notes.html)), and the old core will be removed in the next release ([PR](https://github.com/PennyLaneAI/pennylane/pull/1100)). This means that calls to `qml.enable_tape()` are redundant now and will return an error in the next PennyLane release.
This PR removes calls to `qml.enable_tape()`.
=> Fix: Remove references to PennyLane's tape mode as per PennyLane v0.14

examples/braket_features/Simulating_Noise_On_Amazon_Braket.ipynb
Add example notebook for density matrix simulators on Amazon Braket.
=> Add Simulating noise on Amazon Braket.ipynb

examples/quantum_annealing/Running_large_problems_using_QBSolv.ipynb
N/A
Added a QBSolv parameter 'num_reads' to allow users to adjust the number of shots per task when use QBSolv().sample_qub(...).
=> added num_reads to configure num shots per task in the qbsolv notebook

README.md, examples/advanced_circuits_algorithms/QPE/QPE.ipynb
*Issue #, if available:* #60 
- Added direct links to notebooks from the main README page, along with a 'table of contents'
- Fixed the QPE notebook Example 4 as pointed out by @kjacky in #60 
=> Add links to README; Fix QPE example 4

environment.yml, examples/pennylane/2_Graph_optimization_with_QAOA.ipynb
…ctations
There's a new method for computing Hamiltonian expectations in PennyLane in 0.17 (see https://pennylane.readthedocs.io/en/stable/development/release_notes.html#release-0-17-0) using just `qml.expval`. This PR switches the PennyLane QAOA notebook to use that.
=> Update PennyLane QAOA notebook to use new expval

environment.yml
PySCF 2.0 is incompatible with PennyLane-Qchem:
https://github.com/PennyLaneAI/pennylane/pull/1827
=> Pin PySCF to version < 2.0

environment.yml, test/notebook_tests/test_notebooks.py
- Jobs model configuration changes are added by updating the required packages in environment file. 
- Hyperparameter tuning notebook excluded from tests since it overlaps with PL example. 
=> fix: jobs model dependencies, excluded job examples from tests

environment.yml, examples/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs.ipynb
When running all the cells for notebook at once, it fails at the last cell with KeyError for iteration since metrics are generated within allocated time. Handled the case using if-else statements to address this issue and allow users to re-run the cell when metrics not populated. 
=> fix: metrics timeout issue in hybrid PL notebook

examples/advanced_circuits_algorithms/Grover/Grover.ipynb, examples/advanced_circuits_algorithms/QAA/QAA_tutorial.ipynb, examples/advanced_circuits_algorithms/QFT/QFT.ipynb, examples/advanced_circuits_algorithms/QPE/QPE.ipynb, examples/advanced_circuits_algorithms/Randomness/Randomness_Generation.ipynb, examples/braket_features/Allocating_Qubits_on_QPU_Devices.ipynb, examples/braket_features/Simulating_Noise_On_Amazon_Braket.ipynb, examples/braket_features/TN1_demo_local_vs_non-local_random_circuits.ipynb, examples/braket_features/Verbatim_Compilation.ipynb, examples/getting_started/1_Running_quantum_circuits_on_simulators.ipynb, examples/getting_started/2_Running_quantum_circuits_on_QPU_devices.ipynb, examples/getting_started/3_Deep_dive_into_the_anatomy_of_quantum_circuits.ipynb, examples/getting_started/4_Superdense_coding.ipynb, examples/hybrid_quantum_algorithms/QAOA/QAOA_braket.ipynb, examples/hybrid_quantum_algorithms/VQE_Transverse_Ising/VQE_Transverse_Ising_Model.ipynb
*Issue #, if available:* N/A
*Description of changes:* After making S3 an optional parameter and removing the previous S3 environment configuration cell in https://github.com/aws/amazon-braket-examples/pull/110 a "NOTE" that was no longer needed was lingering. This PR clean-up this along with an unnecessary branching logic in the Grover example.
=> Clean-up example notebooks after introduction of S3 simplification

examples/getting_started/1_Running_quantum_circuits_on_simulators.ipynb
Issue #, if available:
https://app.asana.com/0/1201412419761249/1201895597479544/f
Description of changes:
Added dm1 info that was missing from some documentation. Added link to dev guide to help user choose a simulator.
=> fix: added missing dm1 info in documentation

test/notebook_tests/test_notebooks.py
=> fix: checking all notebooks for unavailable devices.

README.md
*Issue:*
The issue is that links are broken in the README. I did not create an issue as this seems to be a straight-forward fix. 
Changed README links to reflect correct file structure as they are all missing their immediate parent folder. e.g. `examples/getting_started/0_Getting_started.ipynb` becomes `examples/getting_started/0_Getting_started/0_Getting_started.ipynb`
I tested each link to confirm that the functionality was as expected. 
=> Fix broken links in the README Simple Circuits and Algorithms section.

test/notebook_tests/test_notebooks.py
Excluding QML notebook from tests since those run with `instanceType='ml.p3.16xlarge'` for lightning.gpu and are not conflicts with tests schedule with jobs being stuck in QUEUED state. 
=> change: exclude QML notebook from tests

examples/hybrid_jobs/6_QNSPSA_optimizer_with_embedded_simulator/qnspsa_with_embedded_simulator.ipynb, examples/hybrid_jobs/6_QNSPSA_optimizer_with_embedded_simulator/source_scripts/qaoa_large_problem.py
*Issue #, if available:* None
*Description of changes:* 
- Remove the statement that the notebook requires `networkx==2.6.3`, as this dependency has been previously removed. 
- Update the upgrading command for `lightning.gpu` in the job script, reflecting the bug fix from PennyLane on June 30. (https://github.com/PennyLaneAI/pennylane-lightning-gpu/pull/36). Now the job script installs `lightning.gpu` v0.24.1
- Small readability improvements
=> Update package versions for the QNSPSA example.

test/notebook_tests/test_notebooks.py
Temporarily excluding embedded sim notebook from tests since some instances getting stuck for jobs until sagemaker limits are increased.
=> change: exclude embedded sim notebook from tests

examples/braket_features/Verbatim_Compilation.ipynb
OQC's Lucy device does not support `disable_qubit_rewiring=True` any more. Remove it from cell 22 in the "Verbatim Compilation" notebook which is causing validation error currently.
=> fix: run verbatim circuit on OQC device

examples/braket_features/Getting_Started_with_OpenQASM_on_Braket.ipynb
Two links to OpenQASM documentation in the `Getting_Started_with_OpenQASM_on_Braket.ipynb` notebook are broken. The documentation has been moved from the old location https://qiskit.github.io/openqasm/ to the new location at https://openqasm.com/. This change just fixes those links.
=> Fix links to OpenQASM documentation

test/notebook_tests/test_notebooks.py
=> fix: Exclude Aquila notebooks from tests

examples/pennylane/6_Adjoint_gradient_computation/6_Adjoint_gradient_computation.ipynb
- Changed electrons from 8 to 2 
- re-ran the notebook 
- change the text where electrons were said to be used as 8. 
- Changed time required from 30 seconds to 15 seconds. 
=> fix: number of electrons in gradient computation

examples/advanced_circuits_algorithms/Quantum_Fourier_Transform/Quantum_Fourier_Transform.ipynb
The 1/sqrt(2) s should be absorbed into the |+> states to preserve normalization.
=> Fix formula

examples/analog_hamiltonian_simulation/00_Introduction_of_Analog_Hamiltonian_Simulation_with_Rydberg_Atoms.ipynb, examples/analog_hamiltonian_simulation/02_Ordered_phases_in_Rydberg_systems.ipynb, examples/analog_hamiltonian_simulation/03_Parallel_tasks_on_Aquila.ipynb, examples/analog_hamiltonian_simulation/04_Maximum_Independent_Sets_with_Analog_Hamiltonian_Simulation.ipynb, examples/analog_hamiltonian_simulation/05_Running_Analog_Hamiltonian_Simulation_with_local_simulator.ipynb
For the AHS notebooks that use local simulator, we manually set the time steps to 100 so that a) the user experience won't change and b) the integration tests can pass, if we change the default value of time steps in the local simulator. 
=> ahs manually specify steps

examples/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/qaoa/qaoa_algorithm_script.py
`qml.ExpvalCost` is deprecated; `qml.expval` is the correct method for returning expectation values.
=> Replace ExpvalCost with qml.expval

nbi/buildspec.yml
https://docs.anaconda.com/anaconda/install/hashes/Anaconda3-2023.03-Linux-x86_64.sh-hash/
=> fix: update conda version used for NBI builds

nbi/buildspec.yml
https://docs.anaconda.com/free/anaconda/reference/hashes/all/
The previous version has an issue where py_310 is added to packages. Additionally, moving to SHA256 for better security.
=> fix: use sha256 hash instead of md5 and latest conda installer

examples/qiskit/0_Getting_Started.ipynb
The Qiskit provider gets the JAQCD action for each device it finds in its search, and fails if this action isn't present. IonQ Aria does not support JAQCD, causing this notebook to fail.
=> Comment out QPU search cell in Qiskit notebook

environment.yml, examples/qiskit/0_Getting_Started.ipynb
* Bumping qiskit_braket_provider from `0.0.3` to `0.0.4` to release. This fixes an issue with the new Aria device not supporting JAQCD (https://github.com/qiskit-community/qiskit-braket-provider/pull/104)
* Uncommented a disabled cell in the Qiskit example NBI
=> Bump qiskit_braket_provider version

.github/workflows/conda-build.yml, environment.yml, examples/pennylane/3_Hydrogen_Molecule_geometry_with_VQE/3_Hydrogen_Molecule_geometry_with_VQE.ipynb
* Upgrading to the latest PL versions
* Update the VQE example to reference the new location for the `group_observables` method.
* Update the conda build Github action to remove unused libraries to create more space for the build action which were failing because they were running out of space on the Github runners. 
=> Update pennylane version

examples/braket_features/Getting_notifications_when_a_task_completes/Getting_notifications_when_a_task_completes.ipynb
* The library used to render markdown to html (mistune) fails due to the additional whitespace around the code block causing the notebook to not be rendered on github. 
=> fix: remove redundant whitespace

nbi/buildspec.yml
* Increase compression level for the conda environment compressed archive. This reduces the size of the compressed file by 5%. While the compression time is longer, the time to decompress is about the same. 
=> Increase compression level for conda pack

test/integ_tests/requirements.txt, test/integ_tests/test_all_notebooks.py
This is in response to [this issue](https://github.com/aws/amazon-braket-examples/pull/318) where one of our notebooks was not rendering properly in GitHub. With this change, whenever we run our integration tests we'll also test if the notebooks can be converted to HTML.
=> update: add test for conversion to html

nbi/buildspec.yml
This artifact is needed for creating the LCC using the requirements file.
=> fix: add requirements to buildspec artifacts for packaging

requirements.txt
Syncing SDK to https://github.com/amazon-braket/amazon-braket-sdk-python/releases/tag/v1.55.1
=> fix: reverting oq3 variable names to previous versions.

.github/workflows/conda-build.yml
3.0 is no longer supported: https://gallery.ecr.aws/codebuild/amazonlinux2-x86_64-standard
This brings down the run time from `~9.5m` to `~7.5m`.
=> infra: upgrade to the 5.0 image build

test/integ_tests/test_all_notebooks.py
This is temporary while an investigation is conducted. These examples are running normally on Linux and thus will still be published with NBIs.
=> fix: remove AHS examples slow on MacOS

test/integ_tests/hybrid_jobs/8_Creating_Hybrid_Job_Scripts/Creating_your_first_Hybrid_Job_mocks.py, test/integ_tests/test_all_notebooks.py
Add mocks for scripts version of intro jobs notebook (near duplicate of similarly named notebook in folder 0 of hybrid jobs)
Passing in LEAST and ALL
=> test: add mocking for hybrid jobs scripts notebook

requirements.txt
PennyLane notebooks fail with the error
```
AttributeError: module 'ml_dtypes' has no attribute 'float8_e4m3b11'
```
from JAX. JAX is incompatible with the new `ml_dtypes`, so the latter has to be [downgraded to 0.2.0](https://github.com/google/jax/issues/17693#issuecomment-1730176594).
Also had to constrain `ipython<8.17` due to an [issue](https://github.com/ipython/ipython/issues/14230) with the latest IPython release.
=> Add `ml-dtypes==0.2.0` requirement

nbi/buildspec.yml
Tried out `xz`, `bzip2`, and `zstd`. This proved to be the best combination of speed for compression, decompression, and size of the object.
Runtime: `4m 32s`
Object size: `366M	envs/Braket.tar.zst`
The compressed object at `1` was around `400M` but was slightly faster. As this gives a nice space savings with only a small uptick in runtime, this level was added.
For comparison, `xz`:
| Compression Level |`txz` size | Conda action runtime | 
|--------|--------|--------|
| 0 | 388M | 4m 48s |
| 1 | 364M | 4m 58s  |
| 3 | 345 M | 5m 21s |
| 6 | 304M | 6m 40s  | 
The main reason `xz` and `bzip2` were not chosen was due to the longer compression time which added a minimum of 20 seconds to what the current runtimes are.
By submitting this pull …
=> infra: add image size and use zstd to compress the conda env

.gitattributes
This change should make github include the `examples` directory in language stats (as documented here https://github.com/github-linguist/linguist/blob/master/docs/overrides.md) and reflect the usage of Jupyter Notebooks in this repo.
=> Unmark examples folder as documentation for stats

test/integ_tests/test_all_notebooks.py
Testbook defaults to using [`python3`](https://github.com/nteract/testbook/blob/62d7bd9642d70d27a90c6ab7f1d441d13d48a97d/testbook/testbook.py#L31) unless a kernel is specified. Here, we try to use conda_braket and fallback to python3 if the env is not built. This may be the case for local development and execution.
=> update the kernel used by testbook

.github/workflows/conda-build.yml, nbi/buildspec.yml, nbi/codebuild_build.sh, requirements.txt
Runtime drops from 5 minutes to 3 minutes. 
Installing wget is needed as it is not on the local build image. The rest of the needed files are from the miniconda install and will function as before.
Currently, the build utilizes the [standard-5.0](https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/5.0/Dockerfile) image. This contains way more is needed for setting up the conda environment so to reduce developer wait time and Github runner usage time, swapping to the local agent was opted for.
=> Utilize the local build image to expedite docker build times

requirements.txt, test/integ_tests/analog_hamiltonian_simulation/ahs_device_capabilities.json
This will unblock dependabot updates for the new schemas release. There was AHS properties added so this updates the mock to include those.
=> fix: add new fields for the AHS device mock

pyproject.toml, requirements.txt
This is beneficial for custom repos and for repos that are being tested. Also qiskit-terra was renamed to qiskit so we are pulling in both of these due to the naming issue. This prevents dependency issues from occurring.
=> infra: allow hatch to pull in deps referenced by repo and update qiskit-terra to qiskit

pyproject.toml
This allows workers to take up tests if they are idle. This is especially useful for tests where runtimes are not well distributed and one worker may finish way before another.
=> infra: introduce loading steal for parallelized tests

examples/braket_features/Verbatim_Compilation.ipynb
There is one last mentioning of OQC that wasn't removed
Remove the mentioning of "Oxford Quantum circuits"
=> remove mentioning of oxford quantum circuits

requirements.txt, test/integ_tests/test_all_notebooks.py
Notebook takes too long to run.
Also pinned sympy<1.13 (see https://github.com/amazon-braket/amazon-braket-algorithm-library/pull/149)
=> Exclude noisy AHS simulation example from integ tests

examples/braket_features/Verbatim_Compilation.ipynb
Fixing a warning box that didn't include IQM. This has already caused some confusion: https://github.com/qiboteam/qibo-cloud-backends/pull/30#discussion_r1760729625
=> Include IQM in devices with verbatim mode supported

examples/braket_features/Getting_Started_with_OpenQASM_on_Braket.ipynb
*Issue*
In https://github.com/amazon-braket/amazon-braket-examples/blob/main/examples/braket_features/Getting_Started_with_OpenQASM_on_Braket.ipynb -- first of "Advanced OpenQASM features", the
```
int[32] n = 5;
bit[n + 1] c;
qubit[n + 1] q;
```
is invalid OpenQASM. `n` should be a `const`
Ref: https://openqasm.com/language/types.html#arrays citation for this (look for the Note: "Note that bit, bit[n] and stretch are not valid array base types, nor are any quantum types.")
Following the example here: https://openqasm.com/language/types.html#qubits, I made the change 
`int[32] n = 5;` -> `const int[32] n = 5;` in code cell 39 of https://github.com/amazon-braket/amazon-braket-examples/blob/main/examples/braket_features/Getting_Started_with_OpenQASM_on_Braket.ipynb …
=> fix: setting type of array length to const int in OQ3 example

test/integ_tests/test_all_notebooks.py
=> fix: exclude device-dependent tests from test_all_notebooks

requirements.txt
mistune introduced a bug in 3.10 that's causing nbconvert to fail; this change pins the version until the bug is fixed.
=> fix: Pin mistune to 3.0.2

requirements.txt
Braket notebooks are still on an older version of glibc, so we need to keep PennyLane pinned
=> fix: Pin PennyLane

examples/advanced_circuits_algorithms/Randomness/Randomness_Generation.ipynb, examples/braket_features/Allocating_Qubits_on_QPU_Devices.ipynb, examples/braket_features/Getting_Devices_and_Checking_Device_Properties.ipynb, examples/braket_features/Getting_Started_with_OpenQASM_on_Braket.ipynb, examples/braket_features/Noise_models/Noise_models_on_Rigetti.ipynb, examples/braket_features/Verbatim_Compilation.ipynb, examples/getting_started/2_Running_quantum_circuits_on_QPU_devices/2_Running_quantum_circuits_on_QPU_devices.ipynb, examples/getting_started/3_Deep_dive_into_the_anatomy_of_quantum_circuits/3_Deep_dive_into_the_anatomy_of_quantum_circuits.ipynb, examples/hybrid_jobs/0_Creating_your_first_Hybrid_Job/0_Creating_your_first_Hybrid_Job.ipynb, examples/hybrid_jobs/7_Running_notebooks_as_hybrid_jobs/Running_notebooks_as_hybrid_jobs.ipynb, examples/hybrid_jobs/8_Creating_Hybrid_Job_Scripts/Creating_your_first_Hybrid_Job.ipynb, examples/hybrid_quantum_algorithms/QAOA/QAOA_braket.ipynb, examples/hybrid_quantum_algorithms/VQE_Transverse_Ising/VQE_Transverse_Ising_Model.ipynb, examples/pennylane/0_Getting_started/0_Getting_started.ipynb, examples/pulse_control/1_Bringup_experiments.ipynb, examples/pulse_control/2_Native_gate_calibrations.ipynb, examples/pulse_control/3_Bell_pair_with_pulses_Rigetti.ipynb, examples/pulse_control/4_Build_single_qubit_gates.ipynb, requirements.txt
Includes renaming `Ankaa2` enum value to `_Ankaa2` for compatibility with `amazon-braket-sdk` v1.89.1.
=> fix: update to amazon-braket-sdk v1.89.1

examples/pennylane/3_Hydrogen_Molecule_geometry_with_VQE/3_Hydrogen_Molecule_geometry_with_VQE.ipynb
Move `@qnode(dev)` decorated function inside the decorator job
=> fix: define pennylane functions inside decorator job

test/integ_tests/record_utils.py
- additional attributes are required to properly record the notebook when running the script to add notebook mocks specified in the testing readme. 
- Without this call failed for get_quantum_task for one of the notebook, that was excluded from the test. 
- tested with one notebook file which was causing errors to record results.
=> infra: update record utils to handle additional attributes

TESTING.md, examples/advanced_circuits_algorithms/Randomness/Randomness_Generation.ipynb, test/integ_tests/test_all_notebooks.py
…domness notebook from excluded list
- uncomments the notebook commented cell blocks based on the identifier tag so that can run the test end to end for the notebook. 
- currently removed one notebook from the excluded list. 
- ran test with and without least mocking options. 
=> infra: uncomment code blocks programmatically for testing, remove randomness notebook from excluded list
